# You are given two strings, str_1 and str_2, where str_2 is generated by randomly
# shuffling str_1 and then adding one letter at a random position.
#
# Write a function that returns the letter that was added to str_2.
#
# Examples:
#
# csFindAddedLetter(str_1 = "bcde", str_2 = "bcdef") -> "f"
# csFindAddedLetter(str_1 = "", str_2 = "z") -> "z"
# csFindAddedLetter(str_1 = "b", str_2 = "bb") -> "b"
# csFindAddedLetter(str_1 = "bf", str_2 = "bfb") -> "b"
# Notes:
#
# str_1 and str_2 both consist of only lowercase alpha characters.
# [execution time limit] 4 seconds (py3)
#
# [input] string str_1
#
# [input] string str_2
#
# [output] string

def cs_find_added_letter(str_1, str_2):
    str_1 = sorted(str_1)
    str_2 = sorted(str_2)
    for c1, c2 in zip(str_1, str_2):
        if c1 != c2:
            return c2

    return str_2[-1]
